#!/bin/bash

set -e
shopt -s expand_aliases

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

alias apt_update='apt-get update'
alias apt_install='apt-get install -y --no-install-recommends'
alias apt_remove='apt-get purge -y'
alias apt_upgrade='apt-get dist-upgrade -y --no-install-recommends'
alias apt_add_ppa='apt-add-repository -y'


# Default services
# Set 1 to the service you want to disable
export DISABLE_SYSLOG=${DISABLE_SYSLOG:-0}
export DISABLE_CRON=${DISABLE_CRON:-0}
