#!/bin/bash

shopt -s expand_aliases

apt_is_installed() { dpkg -l $1 &>/dev/null; }

apt_remove_if_installed() {
  for pkg in $1; do
    apt_is_installed $pkg && apt-get purge $pkg || true
  done
}

alias apt_update='apt-get update -q'
alias apt_install='apt-get install -y -q --no-install-recommends'
alias apt_remove='apt-get purge -y'
alias apt_upgrade='apt-get dist-upgrade -y --no-install-recommends -o Dpkg::Options::="--force-confold"'
alias apt_add_ppa='apt-add-repository -y'


# Default services
# Set 1 to the service you want to disable
export DISABLE_SYSLOG=${DISABLE_SYSLOG:-0}
export DISABLE_CRON=${DISABLE_CRON:-0}
